# Generated by Django 3.2.25 on 2024-10-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='image/')),
                ('engine_capacity', models.TextField(max_length=150)),
                ('mileage', models.TextField(max_length=150)),
                ('transmission', models.TextField(max_length=150)),
                ('weight', models.TextField(max_length=150)),
                ('fuel_tank', models.TextField(max_length=150)),
                ('power', models.TextField(max_length=150)),
                ('tourque', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ClientLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('password', models.CharField(max_length=25)),
                ('confirmpassword', models.CharField(max_length=25)),
            ],
        ),
    ]
