# Generated by Django 3.2.25 on 2024-09-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='image/')),
                ('engine_capacity', models.TextField(max_length=150)),
                ('malage', models.TextField(max_length=150)),
                ('transmission', models.TextField(max_length=150)),
                ('weight', models.TextField(max_length=150)),
                ('fuel_tank', models.TextField(max_length=150)),
                ('power', models.TextField(max_length=150)),
                ('tourque', models.TextField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Bikes',
        ),
    ]
