# Generated by Django 3.2.25 on 2024-10-04 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_adminlogin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminlogin',
            options={'ordering': ['email'], 'verbose_name_plural': 'Rideitadmin'},
        ),
        migrations.AlterModelTable(
            name='adminlogin',
            table='Rideitadmin',
        ),
    ]
