# Generated by Django 5.1.1 on 2024-10-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('biketype', models.CharField(choices=[('touring', 'Touring'), ('naked', 'Naked'), ('sports', 'Sports'), ('adventure', 'Adventure'), ('cruiser', 'Cruiser'), ('caferacer', 'Cafe Racer')], max_length=20)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='image/')),
                ('engine_capacity', models.TextField(max_length=150)),
                ('mileage', models.TextField(max_length=150)),
                ('transmission', models.TextField(max_length=150)),
                ('weight', models.TextField(max_length=150)),
                ('fuel_tank', models.TextField(max_length=150)),
                ('power', models.TextField(max_length=150)),
                ('tourque', models.TextField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Bike',
        ),
    ]
