# Generated by Django 3.2.25 on 2024-10-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_accessoriesitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminlogin',
            options={},
        ),
        migrations.AlterModelTable(
            name='adminlogin',
            table=None,
        ),
    ]
